---
app_name: "Fiebooth ++"
bp_pin: 18
photos_folder: photos
logs_folder: logs
width_printer: 1280
height_printer: 853
home_delay: 6
user_name: guest
user_password: password
user_text: Mon super mariage !!
user_photos_len: 0
user_prints_len: 0
total_photos_len: 0
total_prints_len: 0
api_enable: true
use_keyboard: true
green_btn: 26
red_btn: 16
yellow_btn: 24
blue_btn: 23
flash_pin: 4
contrast: 0
brightness: 0
contrast_default: -2
brightness_default: +1
thumbnail_factor: 5
wifi_ssid: ma_box
wifi_password: mon_mot_de_passe