---
app_name: "Fiebooth ++"
bp_pin: 18
photos_folder: photos
logs_folder: logs
width_printer: 1280
height_printer: 853
home_delay: 6
user_name: guest
user_password: password
api_enable: true
use_keyboard: true
green_btn: 26
red_btn: 0
yellow_btn: 0
blue_btn: 0
contrast: 0
brightness: 0
contrast_default: -3
brightness_default: +2